"""Isolated beets environment (D9): config generated from musiclib.toml into state/beets/.

Import this module before anything imports beets, so the global ~/.config/beets is never read.
"""

import os
from pathlib import Path

from .config import Config

# D12 layout. %aunique disambiguates two editions of one album.
# D17: folder year is the original release year; tags keep the matched release's date.
YEAR = "%if{$original_year,$original_year,$year}"
PATH_TAIL = "%if{$multidisc,$disc-}$track $title"
CONFIG_TEMPLATE = """\
# Generated by musiclib from musiclib.toml; edits here are overwritten.
directory: @LIBRARY_DIR@
library: @STATE@/library.db
plugins: [musicbrainz, fetchart, embedart, inline]
ignore_hidden: yes

import:
    copy: yes              # SPEC safety rule 2: never move out of the dump
    move: no
    write: yes             # tags are written to the library copies only
    quiet: yes
    quiet_fallback: skip   # weak matches go to review, never guessed (D15)
    timid: no
    resume: no
    incremental: no
    duplicate_action: keep # musiclib resolves duplicates itself (D14)
    log: @STATE@/import.log

match:
    strong_rec_thresh: 0.04   # D15

paths:
    default: $albumartist/@YEAR@ - $album%aunique{}/@PATH_TAIL@
    comp: Compilations/@YEAR@ - $album%aunique{}/@PATH_TAIL@
    singleton: Non-Album/$artist/$title

item_fields:
    multidisc: "1 if disctotal > 1 else ''"   # used by %if{$multidisc,...} in paths

fetchart:
    auto: yes
embedart:
    auto: yes
"""


def setup(cfg: Config) -> Path:
    """Write the beets config and point BEETSDIR at it. Returns the beets state dir."""
    if cfg.library_dir is None:
        raise SystemExit("library_dir is not set in musiclib.toml")
    state = cfg.state_dir / "beets"
    state.mkdir(parents=True, exist_ok=True)
    (state / "config.yaml").write_text(
        CONFIG_TEMPLATE.replace("@LIBRARY_DIR@", str(cfg.library_dir))
        .replace("@STATE@", str(state)).replace("@PATH_TAIL@", PATH_TAIL).replace("@YEAR@", YEAR))
    os.environ["BEETSDIR"] = str(state)

    import beets
    from beets import plugins

    beets.config.clear()
    beets.config.read(user=True, defaults=True)  # user = BEETSDIR/config.yaml, i.e. ours
    assert Path(beets.config.config_dir()) == state, "beets would read the wrong config"
    # clear() dropped the defaults plugins registered at load; reload them fresh.
    # (Private beets registries; beets is pinned in pyproject.)
    plugins._instances.clear()
    plugins.BeetsPlugin.listeners.clear()
    plugins.BeetsPlugin._raw_listeners.clear()
    plugins.load_plugins()
    return state
